# Generated by Django 6.0.3 on 2026-03-20 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0007_mark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='lessons.enrollment')),
                ('group', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='lessons.group')),
                ('student', models.ForeignKey(editable=False, limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
