# Generated by Django 6.0.3 on 2026-03-20 17:34

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_month',
            field=models.PositiveSmallIntegerField(default=payments.models.current_month),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_year',
            field=models.PositiveSmallIntegerField(default=payments.models.current_year),
        ),
    ]
