# Generated by Django 6.0.3 on 2026-03-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('UZBEK', 'Uzbek'), ('ENGLISH', 'English')], default='UZBEK', max_length=30),
        ),
    ]
