# Generated by Django 6.0.3 on 2026-03-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0007_alter_user_options_user_unique_full_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_full_name',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'role'), name='unique_full_name_per_role'),
        ),
    ]
