# Generated by Django 6.0.3 on 2026-03-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_active_profile',
            field=models.BooleanField(default=True),
        ),
    ]
