# Generated by Django 6.0.3 on 2026-04-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
