# Generated by Django 6.0.3 on 2026-03-16 19:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('full_mark', models.PositiveIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exams', to='lessons.group')),
            ],
        ),
    ]
