# Generated by Django 6.0.3 on 2026-03-18 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_exam_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField()),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='marks', to='lessons.enrollment')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='lessons.exam')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exam', 'enrollment'), name='unique_exam_enrollment_mark')],
            },
        ),
    ]
